

                              metastatement  ::=  quantifiedMetastatement

                                               |  bindingAssertion 

                                               ;


                 
                    quantifiedMetastatement  ::=  ( "∀" | "∃" )<NO_WHITESPACE>variable metastatement ;


                           bindingAssertion  ::=  variable "is" ( "bound" | "free" ) "in" metastatement ;


