

                          metastatement  ::=  ( "∀" | "∃" )<NO_WHITESPACE>argument metastatement 

                                           |  argument "is" ( "bound" | "free" ) "in" metastatement

                                           ;

