

                              statement  ::=  ( "∀" | "∃" ) ( ( "[" frameArgument "]" ) | argument ) metaArgument 

                                           |  ( ( "[" frameArgument "]" ) | argument ) "is" ( "bound" | "free" ) "in" metaArgument

                                           ;

