

                              statement  ::=  ( "∀" | "∃" )<NO_WHITESPACE>argument metaArgument 

                                           |  argument "is" ( "bound" | "free" ) "in" metaArgument

                                           ;

